// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sinf_or_cosf_32_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        t_in_V,
        do_cos,
        ap_return
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter6_fsm_state7 = 2'd2;
parameter    ap_ST_iter7_fsm_state8 = 2'd2;
parameter    ap_ST_iter8_fsm_state9 = 2'd2;
parameter    ap_ST_iter9_fsm_state10 = 2'd2;
parameter    ap_ST_iter10_fsm_state11 = 2'd2;
parameter    ap_ST_iter11_fsm_state12 = 2'd2;
parameter    ap_ST_iter12_fsm_state13 = 2'd2;
parameter    ap_ST_iter13_fsm_state14 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;
parameter    ap_ST_iter6_fsm_state0 = 2'd1;
parameter    ap_ST_iter7_fsm_state0 = 2'd1;
parameter    ap_ST_iter8_fsm_state0 = 2'd1;
parameter    ap_ST_iter9_fsm_state0 = 2'd1;
parameter    ap_ST_iter10_fsm_state0 = 2'd1;
parameter    ap_ST_iter11_fsm_state0 = 2'd1;
parameter    ap_ST_iter12_fsm_state0 = 2'd1;
parameter    ap_ST_iter13_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [31:0] t_in_V;
input   do_cos;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
reg   [1:0] ap_CS_iter6_fsm;
wire    ap_CS_iter6_fsm_state0;
reg   [1:0] ap_CS_iter7_fsm;
wire    ap_CS_iter7_fsm_state0;
reg   [1:0] ap_CS_iter8_fsm;
wire    ap_CS_iter8_fsm_state0;
reg   [1:0] ap_CS_iter9_fsm;
wire    ap_CS_iter9_fsm_state0;
reg   [1:0] ap_CS_iter10_fsm;
wire    ap_CS_iter10_fsm_state0;
reg   [1:0] ap_CS_iter11_fsm;
wire    ap_CS_iter11_fsm_state0;
reg   [1:0] ap_CS_iter12_fsm;
wire    ap_CS_iter12_fsm_state0;
reg   [1:0] ap_CS_iter13_fsm;
wire    ap_CS_iter13_fsm_state0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_CS_iter5_fsm_state6;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_CS_iter6_fsm_state7;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_CS_iter7_fsm_state8;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_CS_iter8_fsm_state9;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_CS_iter9_fsm_state10;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_CS_iter10_fsm_state11;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_CS_iter11_fsm_state12;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_CS_iter12_fsm_state13;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_CS_iter13_fsm_state14;
wire   [7:0] hls_hotbm_second_o_2_address0;
reg    hls_hotbm_second_o_2_ce0;
wire   [29:0] hls_hotbm_second_o_2_q0;
wire   [7:0] hls_hotbm_second_o_3_address0;
reg    hls_hotbm_second_o_3_ce0;
wire   [22:0] hls_hotbm_second_o_3_q0;
wire   [7:0] hls_hotbm_second_o_address0;
reg    hls_hotbm_second_o_ce0;
wire   [14:0] hls_hotbm_second_o_q0;
reg   [0:0] do_cos_read_reg_562;
reg   [0:0] ap_reg_pp0_iter1_do_cos_read_reg_562;
reg   [0:0] ap_reg_pp0_iter2_do_cos_read_reg_562;
reg   [0:0] ap_reg_pp0_iter3_do_cos_read_reg_562;
wire   [0:0] tmp_3_fu_158_p3;
reg   [0:0] tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter1_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter2_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter3_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter4_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter5_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter6_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter7_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter8_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter9_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter10_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter11_tmp_3_reg_568;
reg   [0:0] ap_reg_pp0_iter12_tmp_3_reg_568;
wire   [31:0] p_Val2_s_30_fu_172_p3;
reg   [31:0] p_Val2_s_30_reg_573;
reg   [2:0] ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter4_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter5_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter6_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter7_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter8_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter9_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter10_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter11_ret_V_reg_583;
reg   [2:0] ap_reg_pp0_iter12_ret_V_reg_583;
reg   [35:0] x_V_3_reg_589;
reg   [0:0] tmp_6_reg_595;
wire   [35:0] x_V_4_fu_222_p3;
reg   [35:0] x_V_4_reg_600;
reg   [35:0] ap_reg_pp0_iter5_x_V_4_reg_600;
reg   [35:0] ap_reg_pp0_iter6_x_V_4_reg_600;
reg   [35:0] ap_reg_pp0_iter7_x_V_4_reg_600;
reg   [35:0] ap_reg_pp0_iter8_x_V_4_reg_600;
reg   [35:0] ap_reg_pp0_iter9_x_V_4_reg_600;
wire   [0:0] cos_basis_fu_255_p3;
reg   [0:0] cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter5_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter6_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter7_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter8_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter9_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter10_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter11_cos_basis_reg_605;
reg   [0:0] ap_reg_pp0_iter12_cos_basis_reg_605;
wire   [28:0] p_Val2_12_fu_272_p1;
reg   [28:0] p_Val2_12_reg_611;
reg   [28:0] ap_reg_pp0_iter5_p_Val2_12_reg_611;
reg   [21:0] tmp_2_i_reg_616;
wire   [43:0] OP1_V_3_fu_312_p1;
reg   [29:0] p_Val2_13_reg_642;
reg   [29:0] ap_reg_pp0_iter6_p_Val2_13_reg_642;
reg   [29:0] ap_reg_pp0_iter7_p_Val2_13_reg_642;
reg   [29:0] ap_reg_pp0_iter8_p_Val2_13_reg_642;
reg  signed [22:0] hls_hotbm_second_o_5_reg_647;
reg   [14:0] hls_hotbm_second_o_7_reg_652;
reg   [14:0] ap_reg_pp0_iter6_hls_hotbm_second_o_7_reg_652;
reg  signed [14:0] ap_reg_pp0_iter7_hls_hotbm_second_o_7_reg_652;
reg   [21:0] tmp_6_i_reg_667;
reg   [28:0] tmp_7_i_reg_672;
reg   [20:0] tmp_9_i_reg_677;
wire   [36:0] r_V_fu_391_p2;
reg  signed [36:0] r_V_reg_682;
wire   [72:0] grp_fu_410_p2;
reg   [72:0] p_Val2_11_reg_697;
reg   [35:0] result_V_reg_702;
wire   [63:0] tmp_i_fu_305_p1;
wire   [31:0] p_Val2_s_fu_166_p2;
wire   [35:0] grp_fu_183_p0;
wire   [31:0] grp_fu_183_p1;
wire   [66:0] grp_fu_183_p2;
wire   [35:0] x_V_fu_217_p2;
wire   [0:0] tmp_2_fu_228_p10;
wire   [0:0] tmp_1_fu_249_p2;
wire   [0:0] tmp_fu_286_p2;
wire   [0:0] sin_basis_fu_291_p2;
wire   [6:0] p_Result_i_fu_262_p4;
wire   [7:0] p_Result_s_fu_297_p3;
wire   [21:0] grp_fu_315_p0;
wire   [21:0] grp_fu_315_p1;
wire   [28:0] grp_fu_327_p1;
wire   [43:0] grp_fu_315_p2;
wire   [51:0] grp_fu_327_p2;
wire  signed [36:0] p_Val2_9_fu_555_p2;
wire   [35:0] p_Val2_2_fu_368_p3;
wire  signed [36:0] tmp_11_i_fu_379_p1;
wire  signed [36:0] tmp_10_i_fu_375_p1;
wire  signed [36:0] tmp_13_i_cast_fu_388_p1;
wire   [36:0] p_Val2_10_fu_382_p2;
wire   [35:0] Mx_V_read_assign_fu_397_p3;
wire   [35:0] grp_fu_410_p0;
wire   [3:0] p_Result_1_fu_426_p3;
wire   [0:0] tmp_8_fu_432_p18;
wire   [0:0] tmp_s_fu_470_p18;
wire   [36:0] tmp_5_fu_515_p1;
wire   [36:0] p_Val2_4_fu_518_p2;
wire   [30:0] result_V_i_fu_534_p4;
wire   [0:0] tmp_4_fu_508_p3;
wire   [31:0] tmp_7_fu_524_p4;
wire   [31:0] tmp_9_fu_543_p1;
wire   [21:0] p_Val2_9_fu_555_p1;
reg    grp_fu_183_ce;
reg    grp_fu_315_ce;
reg    grp_fu_327_ce;
reg    grp_fu_410_ce;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg   [1:0] ap_NS_iter6_fsm;
reg   [1:0] ap_NS_iter7_fsm;
reg   [1:0] ap_NS_iter8_fsm;
reg   [1:0] ap_NS_iter9_fsm;
reg   [1:0] ap_NS_iter10_fsm;
reg   [1:0] ap_NS_iter11_fsm;
reg   [1:0] ap_NS_iter12_fsm;
reg   [1:0] ap_NS_iter13_fsm;
wire   [66:0] grp_fu_183_p10;
wire   [51:0] grp_fu_327_p10;
wire   [72:0] grp_fu_410_p00;
wire   [36:0] p_Val2_9_fu_555_p10;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_CS_iter6_fsm = 2'd1;
#0 ap_CS_iter7_fsm = 2'd1;
#0 ap_CS_iter8_fsm = 2'd1;
#0 ap_CS_iter9_fsm = 2'd1;
#0 ap_CS_iter10_fsm = 2'd1;
#0 ap_CS_iter11_fsm = 2'd1;
#0 ap_CS_iter12_fsm = 2'd1;
#0 ap_CS_iter13_fsm = 2'd1;
end

sinf_or_cosf_32_3bkb #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_second_o_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_second_o_2_address0),
    .ce0(hls_hotbm_second_o_2_ce0),
    .q0(hls_hotbm_second_o_2_q0)
);

sinf_or_cosf_32_3cud #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_second_o_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_second_o_3_address0),
    .ce0(hls_hotbm_second_o_3_ce0),
    .q0(hls_hotbm_second_o_3_q0)
);

sinf_or_cosf_32_3dEe #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_second_o_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_second_o_address0),
    .ce0(hls_hotbm_second_o_ce0),
    .q0(hls_hotbm_second_o_q0)
);

astar_dist_mul_36eOg #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 67 ))
astar_dist_mul_36eOg_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .din1(grp_fu_183_p1),
    .ce(grp_fu_183_ce),
    .dout(grp_fu_183_p2)
);

astar_dist_mux_83fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
astar_dist_mux_83fYi_U2(
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd1),
    .din7(1'd1),
    .din8(1'd0),
    .din9(ret_V_reg_583),
    .dout(tmp_2_fu_228_p10)
);

astar_dist_mul_22g8j #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 44 ))
astar_dist_mul_22g8j_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_315_p0),
    .din1(grp_fu_315_p1),
    .ce(grp_fu_315_ce),
    .dout(grp_fu_315_p2)
);

astar_dist_mul_23hbi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 52 ))
astar_dist_mul_23hbi_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(hls_hotbm_second_o_5_reg_647),
    .din1(grp_fu_327_p1),
    .ce(grp_fu_327_ce),
    .dout(grp_fu_327_p2)
);

astar_dist_mul_36ibs #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 37 ),
    .dout_WIDTH( 73 ))
astar_dist_mul_36ibs_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_410_p0),
    .din1(r_V_reg_682),
    .ce(grp_fu_410_ce),
    .dout(grp_fu_410_p2)
);

astar_dist_mux_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
astar_dist_mux_16jbC_U6(
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd1),
    .din8(1'd0),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(1'd0),
    .din17(p_Result_1_fu_426_p3),
    .dout(tmp_8_fu_432_p18)
);

astar_dist_mux_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
astar_dist_mux_16jbC_U7(
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd1),
    .din9(1'd1),
    .din10(1'd0),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd1),
    .din15(1'd0),
    .din16(1'd0),
    .din17(p_Result_1_fu_426_p3),
    .dout(tmp_s_fu_470_p18)
);

astar_dist_mul_mukbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 37 ))
astar_dist_mul_mukbM_U8(
    .din0(ap_reg_pp0_iter7_hls_hotbm_second_o_7_reg_652),
    .din1(p_Val2_9_fu_555_p1),
    .dout(p_Val2_9_fu_555_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter10_fsm <= ap_ST_iter10_fsm_state0;
    end else begin
        ap_CS_iter10_fsm <= ap_NS_iter10_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter11_fsm <= ap_ST_iter11_fsm_state0;
    end else begin
        ap_CS_iter11_fsm <= ap_NS_iter11_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter12_fsm <= ap_ST_iter12_fsm_state0;
    end else begin
        ap_CS_iter12_fsm <= ap_NS_iter12_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter13_fsm <= ap_ST_iter13_fsm_state0;
    end else begin
        ap_CS_iter13_fsm <= ap_NS_iter13_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
    end else begin
        ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter7_fsm <= ap_ST_iter7_fsm_state0;
    end else begin
        ap_CS_iter7_fsm <= ap_NS_iter7_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter8_fsm <= ap_ST_iter8_fsm_state0;
    end else begin
        ap_CS_iter8_fsm <= ap_NS_iter8_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter9_fsm <= ap_ST_iter9_fsm_state0;
    end else begin
        ap_CS_iter9_fsm <= ap_NS_iter9_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter10_cos_basis_reg_605 <= ap_reg_pp0_iter9_cos_basis_reg_605;
        ap_reg_pp0_iter10_ret_V_reg_583 <= ap_reg_pp0_iter9_ret_V_reg_583;
        ap_reg_pp0_iter10_tmp_3_reg_568 <= ap_reg_pp0_iter9_tmp_3_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter11_cos_basis_reg_605 <= ap_reg_pp0_iter10_cos_basis_reg_605;
        ap_reg_pp0_iter11_ret_V_reg_583 <= ap_reg_pp0_iter10_ret_V_reg_583;
        ap_reg_pp0_iter11_tmp_3_reg_568 <= ap_reg_pp0_iter10_tmp_3_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter12_cos_basis_reg_605 <= ap_reg_pp0_iter11_cos_basis_reg_605;
        ap_reg_pp0_iter12_ret_V_reg_583 <= ap_reg_pp0_iter11_ret_V_reg_583;
        ap_reg_pp0_iter12_tmp_3_reg_568 <= ap_reg_pp0_iter11_tmp_3_reg_568;
        p_Val2_11_reg_697 <= grp_fu_410_p2;
        result_V_reg_702 <= {{grp_fu_410_p2[71:36]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter1_do_cos_read_reg_562 <= do_cos_read_reg_562;
        ap_reg_pp0_iter1_tmp_3_reg_568 <= tmp_3_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter2_do_cos_read_reg_562 <= ap_reg_pp0_iter1_do_cos_read_reg_562;
        ap_reg_pp0_iter2_tmp_3_reg_568 <= ap_reg_pp0_iter1_tmp_3_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter3_do_cos_read_reg_562 <= ap_reg_pp0_iter2_do_cos_read_reg_562;
        ap_reg_pp0_iter3_tmp_3_reg_568 <= ap_reg_pp0_iter2_tmp_3_reg_568;
        ret_V_reg_583 <= {{grp_fu_183_p2[65:63]}};
        tmp_6_reg_595 <= grp_fu_183_p2[32'd63];
        x_V_3_reg_589 <= {{grp_fu_183_p2[62:27]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter4_ret_V_reg_583 <= ret_V_reg_583;
        ap_reg_pp0_iter4_tmp_3_reg_568 <= ap_reg_pp0_iter3_tmp_3_reg_568;
        cos_basis_reg_605 <= cos_basis_fu_255_p3;
        p_Val2_12_reg_611 <= p_Val2_12_fu_272_p1;
        tmp_2_i_reg_616 <= {{x_V_4_fu_222_p3[28:7]}};
        x_V_4_reg_600 <= x_V_4_fu_222_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter5_cos_basis_reg_605 <= cos_basis_reg_605;
        ap_reg_pp0_iter5_p_Val2_12_reg_611 <= p_Val2_12_reg_611;
        ap_reg_pp0_iter5_ret_V_reg_583 <= ap_reg_pp0_iter4_ret_V_reg_583;
        ap_reg_pp0_iter5_tmp_3_reg_568 <= ap_reg_pp0_iter4_tmp_3_reg_568;
        ap_reg_pp0_iter5_x_V_4_reg_600 <= x_V_4_reg_600;
        hls_hotbm_second_o_5_reg_647 <= hls_hotbm_second_o_3_q0;
        hls_hotbm_second_o_7_reg_652 <= hls_hotbm_second_o_q0;
        p_Val2_13_reg_642 <= hls_hotbm_second_o_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter6_cos_basis_reg_605 <= ap_reg_pp0_iter5_cos_basis_reg_605;
        ap_reg_pp0_iter6_hls_hotbm_second_o_7_reg_652 <= hls_hotbm_second_o_7_reg_652;
        ap_reg_pp0_iter6_p_Val2_13_reg_642 <= p_Val2_13_reg_642;
        ap_reg_pp0_iter6_ret_V_reg_583 <= ap_reg_pp0_iter5_ret_V_reg_583;
        ap_reg_pp0_iter6_tmp_3_reg_568 <= ap_reg_pp0_iter5_tmp_3_reg_568;
        ap_reg_pp0_iter6_x_V_4_reg_600 <= ap_reg_pp0_iter5_x_V_4_reg_600;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter7_cos_basis_reg_605 <= ap_reg_pp0_iter6_cos_basis_reg_605;
        ap_reg_pp0_iter7_hls_hotbm_second_o_7_reg_652 <= ap_reg_pp0_iter6_hls_hotbm_second_o_7_reg_652;
        ap_reg_pp0_iter7_p_Val2_13_reg_642 <= ap_reg_pp0_iter6_p_Val2_13_reg_642;
        ap_reg_pp0_iter7_ret_V_reg_583 <= ap_reg_pp0_iter6_ret_V_reg_583;
        ap_reg_pp0_iter7_tmp_3_reg_568 <= ap_reg_pp0_iter6_tmp_3_reg_568;
        ap_reg_pp0_iter7_x_V_4_reg_600 <= ap_reg_pp0_iter6_x_V_4_reg_600;
        tmp_6_i_reg_667 <= {{grp_fu_315_p2[43:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter8_cos_basis_reg_605 <= ap_reg_pp0_iter7_cos_basis_reg_605;
        ap_reg_pp0_iter8_p_Val2_13_reg_642 <= ap_reg_pp0_iter7_p_Val2_13_reg_642;
        ap_reg_pp0_iter8_ret_V_reg_583 <= ap_reg_pp0_iter7_ret_V_reg_583;
        ap_reg_pp0_iter8_tmp_3_reg_568 <= ap_reg_pp0_iter7_tmp_3_reg_568;
        ap_reg_pp0_iter8_x_V_4_reg_600 <= ap_reg_pp0_iter7_x_V_4_reg_600;
        tmp_7_i_reg_672 <= {{grp_fu_327_p2[51:23]}};
        tmp_9_i_reg_677 <= {{p_Val2_9_fu_555_p2[36:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter9_cos_basis_reg_605 <= ap_reg_pp0_iter8_cos_basis_reg_605;
        ap_reg_pp0_iter9_ret_V_reg_583 <= ap_reg_pp0_iter8_ret_V_reg_583;
        ap_reg_pp0_iter9_tmp_3_reg_568 <= ap_reg_pp0_iter8_tmp_3_reg_568;
        ap_reg_pp0_iter9_x_V_4_reg_600 <= ap_reg_pp0_iter8_x_V_4_reg_600;
        r_V_reg_682 <= r_V_fu_391_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1) & (ap_ce == 1'b1))) begin
        do_cos_read_reg_562 <= do_cos;
        p_Val2_s_30_reg_573 <= p_Val2_s_30_fu_172_p3;
        tmp_3_reg_568 <= t_in_V[32'd31];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter6_fsm_state0) & (1'b1 == ap_CS_iter7_fsm_state0) & (1'b1 == ap_CS_iter8_fsm_state0) & (1'b1 == ap_CS_iter9_fsm_state0) & (1'b1 == ap_CS_iter10_fsm_state0) & (1'b1 == ap_CS_iter11_fsm_state0) & (1'b1 == ap_CS_iter12_fsm_state0) & (1'b1 == ap_CS_iter13_fsm_state0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1) & (ap_ce == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & ((1'b1 == ap_CS_iter1_fsm_state2) | (1'b1 == ap_CS_iter2_fsm_state3) | (1'b1 == ap_CS_iter3_fsm_state4)))) begin
        grp_fu_183_ce = 1'b1;
    end else begin
        grp_fu_183_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & ((1'b1 == ap_CS_iter5_fsm_state6) | (1'b1 == ap_CS_iter6_fsm_state7) | (1'b1 == ap_CS_iter7_fsm_state8)))) begin
        grp_fu_315_ce = 1'b1;
    end else begin
        grp_fu_315_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & ((1'b1 == ap_CS_iter6_fsm_state7) | (1'b1 == ap_CS_iter7_fsm_state8) | (1'b1 == ap_CS_iter8_fsm_state9)))) begin
        grp_fu_327_ce = 1'b1;
    end else begin
        grp_fu_327_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & ((1'b1 == ap_CS_iter10_fsm_state11) | (1'b1 == ap_CS_iter11_fsm_state12) | (1'b1 == ap_CS_iter12_fsm_state13)))) begin
        grp_fu_410_ce = 1'b1;
    end else begin
        grp_fu_410_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b1))) begin
        hls_hotbm_second_o_2_ce0 = 1'b1;
    end else begin
        hls_hotbm_second_o_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b1))) begin
        hls_hotbm_second_o_3_ce0 = 1'b1;
    end else begin
        hls_hotbm_second_o_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b1))) begin
        hls_hotbm_second_o_ce0 = 1'b1;
    end else begin
        hls_hotbm_second_o_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if (((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if (((((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | (ap_CS_iter4_fsm_state5 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter4_fsm_state5) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter10_fsm)
        ap_ST_iter10_fsm_state11 : begin
            if (((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end else if (((((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | (ap_CS_iter9_fsm_state10 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state0;
            end else begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end
        end
        ap_ST_iter10_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter9_fsm_state10) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end else begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter10_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter13_fsm)
        ap_ST_iter13_fsm_state14 : begin
            if (((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b1))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end else if (((ap_ce == 1'b1) & (((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | (ap_CS_iter12_fsm_state13 == 1'b0)))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state0;
            end else begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end
        end
        ap_ST_iter13_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter12_fsm_state13) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end else begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter13_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if (((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if (((((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | (ap_CS_iter3_fsm_state4 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter3_fsm_state4) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter11_fsm)
        ap_ST_iter11_fsm_state12 : begin
            if (((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end else if (((((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | (ap_CS_iter10_fsm_state11 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state0;
            end else begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end
        end
        ap_ST_iter11_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter10_fsm_state11) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end else begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter11_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if (((1'b1 == ap_CS_iter0_fsm_state1) & ~((1'b0 == ap_start) | (ap_ce == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((((ap_CS_iter0_fsm_state1 == 1'b0) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((1'b0 == ap_start) | (ap_ce == 1'b0)))) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter0_fsm_state1) & ~((1'b0 == ap_start) | (ap_ce == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter2_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if (((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if (((((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b0)) | (ap_CS_iter2_fsm_state3 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter2_fsm_state3) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter7_fsm)
        ap_ST_iter7_fsm_state8 : begin
            if (((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else if (((((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | (ap_CS_iter6_fsm_state7 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end
        end
        ap_ST_iter7_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter6_fsm_state7) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter7_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter12_fsm)
        ap_ST_iter12_fsm_state13 : begin
            if (((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end else if (((((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | (ap_CS_iter11_fsm_state12 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state0;
            end else begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end
        end
        ap_ST_iter12_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter11_fsm_state12) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end else begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter12_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter8_fsm)
        ap_ST_iter8_fsm_state9 : begin
            if (((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end else if (((((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | (ap_CS_iter7_fsm_state8 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state0;
            end else begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end
        end
        ap_ST_iter8_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter7_fsm_state8) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end else begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter8_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter6_fsm)
        ap_ST_iter6_fsm_state7 : begin
            if (((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else if (((((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | (ap_CS_iter5_fsm_state6 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end
        end
        ap_ST_iter6_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter5_fsm_state6) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter6_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if (((((1'b1 == ap_CS_iter1_fsm_state2) & (ap_ce == 1'b0)) | (ap_CS_iter1_fsm_state2 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter1_fsm_state2) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter9_fsm)
        ap_ST_iter9_fsm_state10 : begin
            if (((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b1) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end else if (((((1'b1 == ap_CS_iter8_fsm_state9) & (ap_ce == 1'b0)) | (ap_CS_iter8_fsm_state9 == 1'b0)) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state0;
            end else begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end
        end
        ap_ST_iter9_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter8_fsm_state9) & ~((ap_ce == 1'b0) | ((1'b1 == ap_CS_iter9_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter9_fsm_state10) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter10_fsm_state11) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter11_fsm_state12) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter12_fsm_state13) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state0) & (ap_ce == 1'b0)) | ((1'b1 == ap_CS_iter13_fsm_state14) & (ap_ce == 1'b0))))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end else begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter9_fsm = 'bx;
        end
    endcase
end

assign Mx_V_read_assign_fu_397_p3 = ((ap_reg_pp0_iter9_cos_basis_reg_605[0:0] === 1'b1) ? 36'd68719476608 : ap_reg_pp0_iter9_x_V_4_reg_600);

assign OP1_V_3_fu_312_p1 = tmp_2_i_reg_616;

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter10_fsm_state0 = ap_CS_iter10_fsm[32'd0];

assign ap_CS_iter10_fsm_state11 = ap_CS_iter10_fsm[32'd1];

assign ap_CS_iter11_fsm_state0 = ap_CS_iter11_fsm[32'd0];

assign ap_CS_iter11_fsm_state12 = ap_CS_iter11_fsm[32'd1];

assign ap_CS_iter12_fsm_state0 = ap_CS_iter12_fsm[32'd0];

assign ap_CS_iter12_fsm_state13 = ap_CS_iter12_fsm[32'd1];

assign ap_CS_iter13_fsm_state0 = ap_CS_iter13_fsm[32'd0];

assign ap_CS_iter13_fsm_state14 = ap_CS_iter13_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

assign ap_CS_iter6_fsm_state0 = ap_CS_iter6_fsm[32'd0];

assign ap_CS_iter6_fsm_state7 = ap_CS_iter6_fsm[32'd1];

assign ap_CS_iter7_fsm_state0 = ap_CS_iter7_fsm[32'd0];

assign ap_CS_iter7_fsm_state8 = ap_CS_iter7_fsm[32'd1];

assign ap_CS_iter8_fsm_state0 = ap_CS_iter8_fsm[32'd0];

assign ap_CS_iter8_fsm_state9 = ap_CS_iter8_fsm[32'd1];

assign ap_CS_iter9_fsm_state0 = ap_CS_iter9_fsm[32'd0];

assign ap_CS_iter9_fsm_state10 = ap_CS_iter9_fsm[32'd1];

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (1'b0 == ap_start);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = ((tmp_4_fu_508_p3[0:0] === 1'b1) ? tmp_7_fu_524_p4 : tmp_9_fu_543_p1);

assign cos_basis_fu_255_p3 = ((ap_reg_pp0_iter3_do_cos_read_reg_562[0:0] === 1'b1) ? tmp_1_fu_249_p2 : tmp_2_fu_228_p10);

assign grp_fu_183_p0 = 67'd21874088818;

assign grp_fu_183_p1 = grp_fu_183_p10;

assign grp_fu_183_p10 = p_Val2_s_30_reg_573;

assign grp_fu_315_p0 = OP1_V_3_fu_312_p1;

assign grp_fu_315_p1 = OP1_V_3_fu_312_p1;

assign grp_fu_327_p1 = grp_fu_327_p10;

assign grp_fu_327_p10 = ap_reg_pp0_iter5_p_Val2_12_reg_611;

assign grp_fu_410_p0 = grp_fu_410_p00;

assign grp_fu_410_p00 = Mx_V_read_assign_fu_397_p3;

assign hls_hotbm_second_o_2_address0 = tmp_i_fu_305_p1;

assign hls_hotbm_second_o_3_address0 = tmp_i_fu_305_p1;

assign hls_hotbm_second_o_address0 = tmp_i_fu_305_p1;

assign p_Result_1_fu_426_p3 = {{ap_reg_pp0_iter12_tmp_3_reg_568}, {ap_reg_pp0_iter12_ret_V_reg_583}};

assign p_Result_i_fu_262_p4 = {{x_V_4_fu_222_p3[35:29]}};

assign p_Result_s_fu_297_p3 = {{sin_basis_fu_291_p2}, {p_Result_i_fu_262_p4}};

assign p_Val2_10_fu_382_p2 = ($signed(tmp_11_i_fu_379_p1) + $signed(tmp_10_i_fu_375_p1));

assign p_Val2_12_fu_272_p1 = x_V_4_fu_222_p3[28:0];

assign p_Val2_2_fu_368_p3 = {{ap_reg_pp0_iter8_p_Val2_13_reg_642}, {6'd0}};

assign p_Val2_4_fu_518_p2 = (37'd0 - tmp_5_fu_515_p1);

assign p_Val2_9_fu_555_p1 = p_Val2_9_fu_555_p10;

assign p_Val2_9_fu_555_p10 = tmp_6_i_reg_667;

assign p_Val2_s_30_fu_172_p3 = ((tmp_3_fu_158_p3[0:0] === 1'b1) ? p_Val2_s_fu_166_p2 : t_in_V);

assign p_Val2_s_fu_166_p2 = (32'd0 - t_in_V);

assign r_V_fu_391_p2 = ($signed(tmp_13_i_cast_fu_388_p1) + $signed(p_Val2_10_fu_382_p2));

assign result_V_i_fu_534_p4 = {{p_Val2_11_reg_697[71:41]}};

assign sin_basis_fu_291_p2 = (tmp_fu_286_p2 ^ 1'd1);

assign tmp_10_i_fu_375_p1 = $signed(p_Val2_2_fu_368_p3);

assign tmp_11_i_fu_379_p1 = $signed(tmp_7_i_reg_672);

assign tmp_13_i_cast_fu_388_p1 = $signed(tmp_9_i_reg_677);

assign tmp_1_fu_249_p2 = (tmp_2_fu_228_p10 ^ 1'd1);

assign tmp_3_fu_158_p3 = t_in_V[32'd31];

assign tmp_4_fu_508_p3 = ((ap_reg_pp0_iter12_cos_basis_reg_605[0:0] === 1'b1) ? tmp_8_fu_432_p18 : tmp_s_fu_470_p18);

assign tmp_5_fu_515_p1 = result_V_reg_702;

assign tmp_7_fu_524_p4 = {{p_Val2_4_fu_518_p2[36:5]}};

assign tmp_9_fu_543_p1 = result_V_i_fu_534_p4;

assign tmp_fu_286_p2 = (tmp_2_fu_228_p10 ^ ap_reg_pp0_iter3_do_cos_read_reg_562);

assign tmp_i_fu_305_p1 = p_Result_s_fu_297_p3;

assign x_V_4_fu_222_p3 = ((tmp_6_reg_595[0:0] === 1'b1) ? x_V_fu_217_p2 : x_V_3_reg_589);

assign x_V_fu_217_p2 = (36'd0 - x_V_3_reg_589);

endmodule //sinf_or_cosf_32_3_s
